services:
  workspace:
    build:
      dockerfile: ./Dockerfile
      context: ..
      target: workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace

  emulator:
    image: ghcr.io/badrap/emulator:0.21.1
    environment:
      APP_URL: http://workspace:4005/app
