name: Test, build and deploy

on: [push]

# Disable all permissions by default, requiring explicit permission definitions for all jobs.
permissions: {}

jobs:
  check:
    name: Lint & typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Install correct Node.js version
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
      - name: Install correct pnpm version
        run: corepack enable
      - name: Enable pnpm caching (requires that correct Node.js and pnpm versions are already installed)
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: Lint & typecheck
        run: |
          pnpm run typecheck
          pnpm run lint
